[book]
authors = ["ningxilai"]
language = "zh_CN"
multilingual = false
src = "src"
title = "Iris's Note Book"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/ningxilai/ningxilai.github.io"
git-repository-icon = "fa-github"

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
